---
title: "IRF data analysis"
output: html_notebook
---

Так можна встановити пакети
```{r message=FALSE, warning=FALSE, include=FALSE}
install.packages('tidyverse')
```

Ця функція завантажить сторонню бібліотеку (пакет) у робоче середовище
```{r include=FALSE}
library(tidyverse)
```

Прочитаймо дані!
```{r}
df <- read.csv("data/time_series_19-covid-Confirmed.csv")
df
```

Вони не tidy: змінна дати розподілена по колонкам(
```{r}
df <- df %>%
  pivot_longer(cols = - c("Province.State", "Country.Region", "Lat", "Long"),
               names_to = "date",
               values_to = "num",
               names_prefix = "X"
               )
df

write.csv(df, "cases_long.csv", row.names = FALSE)
```

Спробуємо подивитись загальну кількість випадків зараження
```{r}
df$num %>% sum()
```
Півтора мільйони? Навряд чи!
```{r}
df %>%
```




```{r}

```







# old, misc

```{r}
read_add_column <- function(fname) {
  read_csv(fname) 
    %>% mutate(type_of_case = fname)
}

df <-
  list.files(path = "data/", pattern = "time_series_19-covid-.*.csv") %>% 
  paste("data/", ., sep = "") %>%    # з'єднує рядки: назву папки і назву файла
  map_df(~read_add_column(.)) %>%
  mutate()
```

